### ISSUE TITLE
SyntaxError: non-default argument follows default argument

### ISSUE THREAD

**Issue by dongyuanwu** [ncbi/scPopCorn#1]
Hi, I am trying to use scPopCorn. But when I imported this package, the error below would be shown:

> File "C:\Users\wdy\Anaconda3\lib\site-packages\scpopcorn\scpopcorn.py", line 1166
>    def Umap_Result(self, Colors = ColorsG, args):
>                                ^
>SyntaxError: non-default argument follows default argument

I adjusted the `.py` file and exchanged `Colors` and `args`. It did work but `Umap_Result` could not be used anymore. What should I do to fix this problem?

I really appreciate any help in advance.

**Comment by wyjhxq** [comment]
I will look into this and get back to you soon.

**Comment by irmed** [comment]
Hi! I really want to try scpopcorn, but have the same issue. Do you have any updates on this problem?
Thank you a lot in advance!

**Comment by zhumengyan** [comment]
Hi， @wyjhxq 
I also have the problem. AND  I try to modify the code.

Firstly, I change `args` to `*args`, and I reinstall scpopcorn

then, I have error: `SyntaxError: 'return' outside function` ,  so I move four spaces to the right. 

Now, I don't have error when `import scpopcorn` .

**Comment by wyjhxq** [comment]
Hi, @irmed , @dongyuanwu , and @zhumengyan ,

I have fixed the problem. If you have already installed scpopcorn by "pip install scpopcorn", then you need to first uninstall it by "pip uninstall scpopcorn" and then install it again by "pip install scpopcorn -U".

I have tested it and it works fine to me. Let me know whether the new version is good to go!
